modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="the_irregularity"
version="1.0.1"
displayName="The Irregularity"
displayURL="https://mcreator.net/the_irregularity"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Dash_Ketch"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.the_irregularity]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.137,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.the_irregularity]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.the_irregularity]]
    modId="playeranimator"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration